# Generated by Django 3.1 on 2020-09-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200904_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quot',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10),
        ),
    ]
